import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { DESCRIPTION, guidance } from '../skills/clickup-axi/scripts/help.mjs';

const root = new URL('../skills/clickup-axi/', import.meta.url);
const version = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8')).version;
const files = {
  'scripts/version.mjs': `// Generated by scripts/skill.js from package.json.\nexport const VERSION = ${JSON.stringify(version)};\n`,
  'SKILL.md': `---
name: clickup-axi
description: Use to find, read, create, update, move, and close ClickUp tasks, manage tags, post comments, and discover ClickUp workspaces and Lists.
---

# ClickUp AXI

${DESCRIPTION}

This skill includes its CLI in scripts/clickup-axi.mjs. No checkout, npm package,
node_modules, or global CLI install is needed. Resolve <skill-dir> to this skill's
absolute directory. Keep the user's project as the working directory.

${guidance('node "<skill-dir>/scripts/clickup-axi.mjs"').map(line => `- ${line}`).join('\n')}
`,
};

for (const [name, content] of Object.entries(files)) {
  const target = new URL(name, root);
  if (process.argv[2] === '--check') {
    if (readFileSync(target, 'utf8') !== content) {
      console.error(`${name} is stale. Run npm run skill.`);
      process.exitCode = 1;
    }
  } else {
    mkdirSync(new URL('.', target), { recursive: true });
    writeFileSync(target, content);
  }
}
